---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hunger
  labels:
    app: hunger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hunger
  template:
    metadata:
      labels:
        app: hunger
    spec:
      containers:
        - name: hunger
          image: username/hunger:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: store owner
  labels:
    app: store owner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store owner
  template:
    metadata:
      labels:
        app: store owner
    spec:
      containers:
        - name: store owner
          image: username/store owner:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rider
  labels:
    app: rider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rider
  template:
    metadata:
      labels:
        app: rider
    spec:
      containers:
        - name: rider
          image: username/rider:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: hunger
  labels:
    app: hunger
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hunger


---


apiVersion: v1
kind: Service
metadata:
  name: store owner
  labels:
    app: store owner
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: store owner


---


apiVersion: v1
kind: Service
metadata:
  name: rider
  labels:
    app: rider
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: rider

